# CLI tools
brew "bat"
brew "carapace"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "htop"
brew "just"
brew "imagemagick"
brew "lazygit"
brew "neovim"
brew "pam-reattach"
brew "ripgrep"
brew "tmux"
brew "uv"
brew "watch"
brew "wget"
brew "yazi"
brew "zoxide"

# Casks
cask "hammerspoon"
cask "iterm2"

# Fonts
cask "font-hack-nerd-font"
