set -g default-shell $SHELL
set -g set-clipboard on

set -g allow-passthrough on
set -g bell-action any
set -g monitor-bell on

set -g default-terminal 'tmux-256color'
set -g terminal-overrides ',xterm-256color:Tc'

set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -g escape-time 0  # disable delays on escape sequences
set -g repeat-time 1000  # increase "prefix-free" window

# 1-based indexing and renumbering
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set-window-option -g mode-keys vi

# session management
bind X kill-session
unbind o
bind-key o run-shell "sesh last || true"  # robust last session keybinding
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# sesh
bind-key "t" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 3 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

set -g status-position top
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=grey]#S"
set -g window-status-format "#{?#{==:#{@claude_status},waiting},#[fg=red],}●#{?#{@claude_status}, [#{@claude_status}],}"
set -g window-status-current-format "#{?#{==:#{@claude_status},waiting},#[fg=red],#{?window_zoomed_flag,#[fg=yellow],#[fg=green]}}●#{?#{@claude_status}, [#{@claude_status}],}"
set -g window-status-current-style "fg=green"
set -g window-status-bell-style "fg=red"
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=green,dim
set -g message-style "fg=green"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux-yank vim-like keybindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# support yanking to system clipboard on remote sessions
set -g @override_copy_command 'tmux load-buffer -w -'

run '~/.config/tmux/plugins/tpm/tpm'
